
package com.evaluacion;


public class PanelCentral extends javax.swing.JFrame {

    
    public PanelCentral() {
        initComponents();
        salida.setText("");
        salida1.setText("");
        salida2.setText("");
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        x1 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        x2 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        y1 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        x3 = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        y2 = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        y3 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        siniestroX = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        siniestroY = new javax.swing.JTextPane();
        salida = new javax.swing.JLabel();
        salida1 = new javax.swing.JLabel();
        salida2 = new javax.swing.JLabel();
        salida3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane3.setViewportView(x1);

        jScrollPane6.setViewportView(x2);

        jLabel1.setText("Coordenadas del siniestro");

        jLabel2.setText("Estacion 1");

        jLabel3.setText("Estacion 2");

        jLabel4.setText("Estacion 3");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane9.setViewportView(y1);

        jScrollPane10.setViewportView(x3);

        jScrollPane11.setViewportView(y2);

        jScrollPane12.setViewportView(y3);

        jLabel5.setText("Coordenadas de estaciones");

        jScrollPane13.setViewportView(siniestroX);

        jScrollPane14.setViewportView(siniestroY);

        salida.setText("jLabel6");

        salida1.setText("jLabel6");

        salida2.setText("jLabel6");

        salida3.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salida3)
                    .addComponent(salida2)
                    .addComponent(salida1)
                    .addComponent(salida))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(57, 57, 57))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salida1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salida2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salida3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CentroOperaciones centroOperaciones = new CentroOperaciones();
        int[] coordenadasCO = new int[2];
        
        //centro de operaciones está en las coordenadas 0,0
        coordenadasCO[0] = 0;
        coordenadasCO[1] = 0;
        centroOperaciones.setCoordenadasCO(coordenadasCO);
        
        //número máximo de estaciones
        int numeroEstaciones = 3;
        if(numeroEstaciones <= 5){
            centroOperaciones.setNumeroEstaciones(numeroEstaciones);
        }else{
            System.out.println("Estaciones máximas deben ser 5");
        }
        
        //Creamos las estaciones
        //estacion 1
        EstBombero estacion1 = new EstBombero();
        estacion1.setCodigoEstacion(1);
        double[] coordenadas1 = {Double.valueOf(x1.getText()),Double.valueOf(y1.getText())};
        estacion1.setCoordenadasEstacion(coordenadas1);
        
        //estacion2
        EstBombero estacion2 = new EstBombero();
        estacion2.setCodigoEstacion(2);
        double[] coordenadas2 = {Double.valueOf(x2.getText()),Double.valueOf(y2.getText())};
        estacion2.setCoordenadasEstacion(coordenadas2);
        
        
        //estacion 3
        EstBombero estacion3 = new EstBombero(); 
        estacion3.setCodigoEstacion(2);
        double[] coordenadas3 = {Double.valueOf(x3.getText()),Double.valueOf(y3.getText())};
        estacion3.setCoordenadasEstacion(coordenadas3);

        //guardamos las estaciones en una coleccion llamada EST
        EstBombero EST[] = {estacion1,estacion2,estacion3};
        
        //creamos el siniestro y le pasamos sus coordenadas del incendio
        Siniestro incendio = new Siniestro();
        double[]coordernadasSiniestro = {Double.valueOf(siniestroX.getText()),Double.valueOf(siniestroY.getText())};
        incendio.setCoordenadasIncendio(coordernadasSiniestro);
        
        double coordenadaSiniestroX = (incendio.getCoordenadasIncendio()[0]);
        double coordenadaSiniestroY = (incendio.getCoordenadasIncendio()[1]);
        double coordenadaEstacionX;
        double coordenadaEstacionY;
        
        double[] distancia = new double[3];


        for(int i = 0; i < EST.length ; i++ ){
            coordenadaEstacionX = EST[i].getCoordenadasEstacion()[0];
            coordenadaEstacionY = EST[i].getCoordenadasEstacion()[1];
            double distanciaX = coordenadaSiniestroX - coordenadaEstacionX;
            double distanciaY = coordenadaSiniestroY - coordenadaEstacionY;      
            distancia[i] = Math.sqrt(Math.pow(distanciaX,2) + Math.pow(distanciaY,2));     
            
        }
        
        double menor = 0;
        int indice = 0;
        for(int i = 0; i < distancia.length; i++){
            
            if(i == 0){
                menor = distancia[i];      
            }else{
            
                if(distancia[i] < menor ){
                    menor = distancia[i];
                    indice = i;
                }
                    
            }
        }
        int estacionAtendera = indice + 1;
        
        salida.setText("Atenderá el incendio:");
        salida1.setText("Estación: " + String.valueOf(estacionAtendera));
        salida2.setText("CoordenadaX: "+ EST[indice].getCoordenadasEstacion()[0]);
        salida3.setText("CoordenadaY: "+ EST[indice].getCoordenadasEstacion()[1]);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelCentral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel salida;
    private javax.swing.JLabel salida1;
    private javax.swing.JLabel salida2;
    private javax.swing.JLabel salida3;
    private javax.swing.JTextPane siniestroX;
    private javax.swing.JTextPane siniestroY;
    private javax.swing.JTextPane x1;
    private javax.swing.JTextPane x2;
    private javax.swing.JTextPane x3;
    private javax.swing.JTextPane y1;
    private javax.swing.JTextPane y2;
    private javax.swing.JTextPane y3;
    // End of variables declaration//GEN-END:variables
}
